apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: micro-market
resources:
  - namespace.yaml
  - secrets.yaml
  - grafana-otel.yaml
  - checkout.yaml
  - inventory.yaml
  - invoice.yaml
  - redis.yaml
